"""posts table

Revision ID: 00c0b4df9a40
Revises: b68008e91041
Create Date: 2019-06-16 19:40:17.328940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00c0b4df9a40'
down_revision = 'b68008e91041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('house',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('SalePrice', sa.Float(), nullable=True),
    sa.Column('MSSubClass', sa.Enum('A', 'C', 'FV', 'I', 'RH', 'RL', 'RP', 'RM', name='mszoning'), nullable=True),
    sa.Column('LotArea', sa.Float(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_house_SalePrice'), 'house', ['SalePrice'], unique=False)
    op.create_index(op.f('ix_house_created'), 'house', ['created'], unique=False)
    op.create_index(op.f('ix_house_updated'), 'house', ['updated'], unique=False)
    op.add_column('user', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_created'), 'user', ['created'], unique=False)
    op.create_index(op.f('ix_user_updated'), 'user', ['updated'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_updated'), table_name='user')
    op.drop_index(op.f('ix_user_created'), table_name='user')
    op.drop_column('user', 'updated')
    op.drop_column('user', 'created')
    op.drop_index(op.f('ix_house_updated'), table_name='house')
    op.drop_index(op.f('ix_house_created'), table_name='house')
    op.drop_index(op.f('ix_house_SalePrice'), table_name='house')
    op.drop_table('house')
    # ### end Alembic commands ###
