"""new field in user model

Revision ID: cc1433e9f775
Revises: 00c0b4df9a40
Create Date: 2019-06-19 22:09:55.644294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1433e9f775'
down_revision = '00c0b4df9a40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_visit', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_visit')
    # ### end Alembic commands ###
